summary: ROS Layer

description: |
  A description of ROS layer.

services:

  test:
    override: replace
    summary: test
    command: /bin/bash -c  "cd $WORKSPACE && printenv > /root/test.txt; while [ true ]; do pwd; sleep 1; done"
    startup: disabled
    on-failure: ignore

  dependencies:
    override: replace
    summary: Installs dependencies of robot
    command: /bin/bash -c "pebble stop launch; cd $WORKSPACE && rosdep install --from-paths src --ignore-src -r -y; pebble start build; pebble stop dependencies;"
    startup: enabled
    on-failure: ignore

  build:
    override: replace
    summary: Builds robot codes
    startup: disabled
    command: /bin/bash -c "cd $WORKSPACE && colcon build; pebble start launch; pebble stop build;"
    on-failure: ignore

  launch:
    override: replace
    summary: Launches robot
    startup: disabled
    command: /bin/bash -c "source $WORKSPACE/install/setup.bash; ros2 run examples_rclcpp_minimal_publisher publisher_member_function; pebble stop launch"
    on-failure: ignore

  api_pipe:
    override: replace
    summary: CLI bridge ;)
    startup: disabled
    command: /bin/bash -c "while [ true ]; do echo "waiting for command\n"; eval $(cat $PIPES/api/request) > $PIPES/api/response; echo "output sent\n"; done"
    on-failure: ignore
