summary: ROS Layer

description: |
  A description of ROS layer.

services:
  test:
    override: replace
    summary: test
    command: /bin/bash -c "while [ true ]; do echo $WORKSPACE; sleep 1; done"
    startup: disabled
    environment:
      VAR1: val1
      VAR2: val2
      VAR3: val3
    on-failure: ignore
  dependencies:
    override: replace
    summary: Installs dependencies of robot
    command: /bin/bash -c "cd $WORKSPACE && rosdep install --from-paths src --ignore-src -r -y"
    startup: disabled
    environment:
      VAR1: val1
      VAR2: val2
      VAR3: val3
    on-failure: shutdown

  build:
    override: replace
    summary: Builds robot codes
    startup: disabled
    command: /bin/bash -c "cd $WORKSPACE && colcon build"
    after:
    - dependencies
    on-failure: shutdown
