summary: ROS Layer

description: |
  A description of ROS layer.

services:

  dependencies:
    override: replace
    summary: Installs dependencies of robot
    command: /bin/bash -c "cd $WORKSPACE && rosdep install --from-paths src --ignore-src -r -y"
    startup: disabled
    on-failure: ignore

  build:
    override: replace
    summary: Builds robot codes
    startup: disabled
    command: /bin/bash -c "cd $WORKSPACE && colcon build"
    on-failure: ignore

  launch:
    override: replace
    summary: Builds robot codes
    startup: disabled
    command: /bin/bash -c "source ~/.bashrc && cd $WORKSPACE && ros2 run examples_rclcpp_minimal_publisher publisher_member_function"
    on-failure: ignore
