summary: ROS Layer

description: |
  A description of ROS layer.

services:
  dependencies:
    override: replace
    summary: Installs dependencies of robot
    command: /bin/bash -c "cd $WORKSPACE && rosdep install --from-paths src --ignore-src -r -y"
    startup: disabled
    before:
    - build
    environment:
      VAR1: val1
      VAR2: val2
      VAR3: val3
    on-failure: ignore

  build:
    override: replace
    summary: Builds robot codes
    startup: disabled
    command: /bin/bash -c "colcon build"
    requires:
    - dependencies
    on-failure: ignore
